### ISSUE TITLE
Risk invariance theorem proof to appendix

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#100]
It is clear in this context what this proof is about. I don't think we need to number it or name the theorem. Also, you need a QED at the end.

<img width="607" alt="screen shot 2016-10-26 at 18 30 15" src="https://cloud.githubusercontent.com/assets/544572/19735078/559f305c-9baa-11e6-99c8-c4b55bf1e603.png">

**Comment by OrfeasLitos** [comment]
I have left it there because we haven't checked it already. I will move it to the appendix once thoroughly discussed. Put qed. I leave the issue open until the proof is ok and moved.
