### ISSUE TITLE
Notation simplification for capital

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#101]
We don't use this notation, so the turn omission comment is useless. Let's remove it.

<img width="830" alt="screen shot 2016-10-26 at 18 35 37" src="https://cloud.githubusercontent.com/assets/544572/19735252/1d323772-9bab-11e6-8491-884906063cde.png">

**Comment by OrfeasLitos** [comment]
Fixed it for both assets and capital. Note: the definition of Assets is never used, but it should be there to remind us why reducing outgoing trust isn't part of the conservative strategy.
