### ISSUE TITLE
properly cite material from a lecture (flow decomposition)

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#108]

**Comment by OrfeasLitos** [comment]
Its citation is \bibitem{flowdecomp}.

**Comment by dionyziz** [comment]
What help do you need here?

**Comment by OrfeasLitos** [comment]
The guides don't point out exactly what kind of information is required when citing a lecture. The slides do not show a date, a prof. name and other crucial data. Moreover, the particular lecture doesn't include formal proofs and stuff so I'm not sure it's very valid, but it's the best I found without searching all the internets. Also flow decomposition is well established.

**Comment by OrfeasLitos** [comment]
Probably the best is to treat it like a webpage reference and be done.

**Comment by dionyziz** [comment]
Can't you find the same results in a book or paper or lecture notes?

**Comment by OrfeasLitos** [comment]
I will leave it open until I find a better reference

**Comment by OrfeasLitos** [comment]
Ahuja, R. K., Magnanti, T. L., & Orlin, J. B. (1993). Network flows: theory, algorithms, and applications. Prentice-Hall (1993)
