### ISSUE TITLE
Consider amiller's references

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#110]
For references and for related work:

trustdavis
http://earlbarr.com/publications/trustdavis.pdf

social collateral
http://www.personal.ceu.hu/staff/Adam_Szeidl/papers/socialcollateral.pdf

ripple classic
http://archive.ripple-project.org/decentralizedcurrency.pdf

**Comment by OrfeasLitos** [comment]
Trust and social collateral is in.
