### ISSUE TITLE
Consider Caronni reference

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#113]
Check Caronni's paper and consider adding a reference.

**Comment by OrfeasLitos** [comment]
link?

**Comment by dionyziz** [comment]
Check your email

**Comment by dionyziz** [comment]
Here for reference:

https://pdfs.semanticscholar.org/7cf5/6cc25a32c4ee6bb5df0ec372e38862d4dbc6.pdf
