### ISSUE TITLE
Lemma 1 proof cleanup

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#120]
This proof is generally pretty well written. I have a few minor comments that will make it slightly shorter and clearer.

**Without loss of generality**

The "without loss of generality" statement is not saying anything:

<img width="710" alt="screen shot 2016-10-28 at 17 32 22" src="https://cloud.githubusercontent.com/assets/544572/19812103/87a26494-9d34-11e6-9e7f-072d3b7c3871.png">

If you look at the theorem statement, it just talks about a game graph and an execution on top of it. In the way we define TransitiveGame, G, the first parameter to the TransitiveGame function, is the initial graph. So there's no need to state it here at all.

**MaxFlow algorithm**

This is too verbose:

<img width="719" alt="screen shot 2016-10-28 at 17 34 44" src="https://cloud.githubusercontent.com/assets/544572/19812197/e0f56be0-9d34-11e6-9388-452e72a84537.png">

Let's rephrase as follows:

"Let $X = \{x_{vw}\}_{\mathcal{V} \cross \mathcal{V}}$ be the flows returned by $MaxFlow(A, B)$."

The fact that MaxFlow is executed on $G$ is specified in the theorem statement and is not needed here.

**DAG argument**

The "directed weighted graph" and "over $G$" portions can be removed, as they are clear from the context:

<img width="725" alt="screen shot 2016-10-28 at 17 39 09" src="https://cloud.githubusercontent.com/assets/544572/19812352/7891721e-9d35-11e6-8f53-babddce54243.png">

**Total order phrasing**

This can be rephrased:

<img width="716" alt="screen shot 2016-10-28 at 17 41 03" src="https://cloud.githubusercontent.com/assets/544572/19812427/bb972f68-9d35-11e6-9b8d-ed23ceba82ca.png">

Into: "Topologically sort this DAG to obtain a total order of its nodes such that: $\forall v, w: v < w => x_{wv} = 0$ [11]. Put differently, there is no flow from larger to smaller nodes."

The sentence "We execute the topological sort on $X$ and obtain a total order of the nodes, such that $B$ is the maximum and $A$ is the minimum node." can be removed completely – it's not saying anything new. You already said you wanted to toposort, and you are later saying that $A$ is min and $B$ is max.

**Rename algorithm 4 to transitive game**

<img width="706" alt="screen shot 2016-10-28 at 17 45 22" src="https://cloud.githubusercontent.com/assets/544572/19812566/5f5d178e-9d36-11e6-86d3-0e791fb31d59.png">

**in-neighbour**

Let's use a dash here for clarity:

<img width="259" alt="screen shot 2016-10-28 at 17 47 09" src="https://cloud.githubusercontent.com/assets/544572/19812616/98be0f7e-9d36-11e6-848b-baa4df678ace.png">

**Total order is followed inversely**

Orders are typically followed in ascending order. In our proof, we traverse the total order in descending order. Maybe we can rephrase here for clarity? "following the total order inversely" or "following the total order in reverse" help in clarifying this.

<img width="702" alt="screen shot 2016-10-28 at 17 49 46" src="https://cloud.githubusercontent.com/assets/544572/19812732/07090ede-9d37-11e6-90c6-bd36b536ea6b.png">

**Confusing letter reuse in induction**

You're using $j$ both for the strong induction hypothesis ($\forall j \in [k]$) but also in your step ($j = k + 1$). Let's use $i$ in the induction hypothesis instead?

<img width="718" alt="screen shot 2016-10-28 at 17 52 27" src="https://cloud.githubusercontent.com/assets/544572/19812796/53a18d0c-9d37-11e6-9d5f-8bc4207e64ab.png">

**Rephrase and remove "obvious"**

This is a complicated proof, let's not look down on our readers :)

<img width="698" alt="screen shot 2016-10-28 at 17 56 59" src="https://cloud.githubusercontent.com/assets/544572/19812980/f4150656-9d37-11e6-8c06-d595a9bf13b8.png">

This can be better phrased as "Since there remains no Angry player, $j_2$ is a convergence turn." Further down the line, I think we can also remove the phrase " It is also obvious that".

**Comment by OrfeasLitos** [comment]
All done with minor deviations from suggestions
