### ISSUE TITLE
Simplify conservative world theorem proof

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#124]
This proof can be simplified quite a bit. First of all you don't need to talk about $\mathcal{G}_j$ as you are not using it. You don't need to talk about the sequence $(j_k)$ at all. Here's an attempt:

Let $\mathcal{H}$ be the game history and suppose there are some stealing actions taking place. Then let $\mathcal{H}'$ be the subsequence of turns each containing at least one Steal action. This subsequence must have a first element. But the player corresponding to that turn plays the Conservative strategy, which is a contradiction.

I think this is both precise and clear. Therefore we do not even need a proof sketch.

**Comment by OrfeasLitos** [comment]
Rephrased and inserted
