### ISSUE TITLE
Use antonopoulos citation for multisig

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#125]
A book is better than a magazine ;)

Antonopoulos, Andreas M. Mastering Bitcoin: unlocking digital cryptocurrencies. " O'Reilly Media, Inc.", 2014.

**Comment by dionyziz** [comment]
It also mentions UTXO and is [creative commons licensed](https://github.com/bitcoinbook/bitcoinbook/tree/7c552ea5cfbc19448635b36407761b377ff5cbe9)

**Comment by dionyziz** [comment]
(so we can completely remove [3][4])

**Comment by OrfeasLitos** [comment]
Nice!
