### ISSUE TITLE
This formalism does not add any value

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#129]
It just takes up space. The description above is already crystal clear.

<img width="482" alt="screen shot 2016-10-29 at 01 09 46" src="https://cloud.githubusercontent.com/assets/544572/19824980/742cf7b8-9d74-11e6-819a-0f3dc4a19eb6.png">

**Comment by OrfeasLitos** [comment]
You're right, I'm removing it.
