### ISSUE TITLE
Weight functions

### ISSUE THREAD

**Issue by dimkarakostas** [OrfeasLitos/TrustIsRisk#132]
c_j is not clearly described. Add an intuitive description for these functions in Definition 1.

**Comment by OrfeasLitos** [comment]
"the weights represent the amount of value attached to the corresponding direct trust" in the paragraph following definition 1. Is it not clear enough?

**Comment by dimkarakostas** [comment]
From my perspective, not really. There is no mention that the functions c_j are actually the weights, although it is implied given that c_j domain is the edges and the codomain is the real numbers.

**Comment by OrfeasLitos** [comment]
Rephrasing the definition:

"Also, since the graphs are weighted, there exists a sequence of _weight_ functions (c j ) with c j : E j → R +"

Tell me what you think.

**Comment by dimkarakostas** [comment]
Yeah, I think that is very good.
