### ISSUE TITLE
Describe Node states

### ISSUE THREAD

**Issue by dimkarakostas** [OrfeasLitos/TrustIsRisk#133]
Node states (Angry/Happy/Sad) are not defined intuitively

**Comment by OrfeasLitos** [comment]
"Moreover, each conservative player can be
in one of three states: Happy, Angry or Sad. Happy players have 0 loss,
Angry players have positive loss and positive incoming trust, thus are
able to replenish their loss at least in part and Sad players have positive
loss, but 0 incoming trust, thus they cannot replenish the loss."

Added this before the Transitive Game.
