### ISSUE TITLE
restore keywords after abstract?

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#143]
It can't be readily inserted, we need to shorten 1-2 lines more somehow.

**Comment by dionyziz** [comment]
If we're exactly tight on space, let's leave it as it is without the keywords.

**Comment by OrfeasLitos** [comment]
I managed to sneak them in by changing this:
![oldsybilres](https://cloud.githubusercontent.com/assets/18602747/20176895/e3733232-a741-11e6-978a-65b21cb23a4d.png)

to this:
![newsybilres](https://cloud.githubusercontent.com/assets/18602747/20176899/e8290d38-a741-11e6-8683-7eb2b9338eed.png)

**Comment by dionyziz** [comment]
LGTM
