### ISSUE TITLE
split paper into several .tex files

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#147]

**Comment by OrfeasLitos** [comment]
preamble.sty complete

**Comment by dionyziz** [comment]
you can try doing this in the form of a pull request while you're at it

**Comment by OrfeasLitos** [comment]
Let's test what I have understood...

**Comment by OrfeasLitos** [comment]
\subimport{}{} fails when I try to import a file with the same name as the one I am editing, even though the file to import is in another directory...
