### ISSUE TITLE
Explain that one can express trust maximally in terms of their capital (FC001)

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#157]
Add a paragraph to the introduction.

**Comment by dionyziz** [comment]
One can express her trust maximally -> Observe that we make the design choice that one can express her trust maximally

**Comment by dionyziz** [comment]
We thus take advantage of the remarkable property of money to normalise subjective human preferences into objective value.

**Comment by dionyziz** [comment]
that she does not trust to great extents ->  that she does not find trustworthy to a great extent

**Comment by dionyziz** [comment]
remove "t and thus has a unique opportunity of expressing in a formal and absolute way its credence by publishing its incoming and outgoing trust."

**Comment by dionyziz** [comment]
Last paragraph of page 3 / first paragraph of page 4: Trust is generally indirect trust

**Comment by dionyziz** [comment]
Definition Assets: Direct trust

**Comment by dionyziz** [comment]
all the money entrusted to her -> all the money directly entrusted to her

**Comment by dionyziz** [comment]
remove ", or simply trust, "
