### ISSUE TITLE
Replace all "trust" with "direct trust" or "indirect trust" accordingly (FC0012)

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#164]
Issue motivated by "When yB<0, we say that A reduces her trust to B by -yB" in Add() explanation from one reviewer, by the abstract and the introduction from another.

Another note to reinforce our proposition that Trust is defined as risk is needed.

**Comment by dionyziz** [comment]
Last paragraph of page 1: Change the first twos Bobs to Charlie (but not at the top of page 2). First paragraph of page 2: Change "we" to `$Alice$`

Joining the network will be done by explicitly entrusting -> $Alice$ joins the network by explicitly entrusting...

**Comment by dionyziz** [comment]
Fig.1, Fig.2 trusts -> indirectly trusts

**Comment by dionyziz** [comment]
The existing willing risk -> The existing voluntary risk

**Comment by dionyziz** [comment]
if she has entrusted no value to any other user. -> if she has not directly entrusted any value to any other user.

**Comment by dionyziz** [comment]
TrustIsRisk  -> Trust Is Risk

**Comment by dionyziz** [comment]
We thus take advantage of the remarkable property of money to normalise subjective human preferences into objective value.
