### ISSUE TITLE
Compare with certain related work (FC009)

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#165]
Ripple
Stellar
SilentWhispers
Privacy Preserving Payments in Credit Networks
RWC 2017 Presentation by Pedro Moreno-Sanchez and Aniket Kate: Listening to and Silencing the Whispers of Ripple: Study and Solutions for Privacy in IOweYou Credit Networks

**Comment by OrfeasLitos** [comment]
k-Anonymous Reputation & On the Limits of Privacy in Reputation Systems prove interesting results that do not apply to our system. They speak about ratings resulting in global reputation, we speak about subjective trust. However, some of their results seem vaguely relevant to our system.

**Comment by OrfeasLitos** [comment]
Ripple was already documented through IOU, added a specific reference to it.
Stellar also referenced
SilentWhispers, PrivPay referenced

**Comment by dionyziz** [comment]
Readers are urged to adhere to the definitions of direct and indirect
trust as proposed in this work and not to extrapolate their meanings, as
suggested by [25]. 

->

We agree with the work of [25] in that the meaning of trust should not be extrapolated. We have adopted their advice in our paper and urge our readers to adhere to the definitions of \textit{direct} and \textit{indirect} trust as they are used here.
