### ISSUE TITLE
Add Cap(v,0...j-1) as input for strategy[v]() (FC014)

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#170]
Change full knowledge to be also other players' capitals and point out that players don't have full knowledge when choosing a move, but that only the others' capitals are missing. Furthermore, explain that in a real-world situation, this may not be the case as out-of-band means and traffic analysis techniques may be employed.

**Comment by OrfeasLitos** [comment]
Solved by commit b367bc8.

**Comment by OrfeasLitos** [comment]
Need to add back v as input to strategy(), add Cap as input to each individual strategy as well.

**Comment by dionyziz** [comment]
In the Transitive Game algorithm:

* Line 6: Change `vStrategy` to `strategy[v]`
* Line 6: Include capital in parameter
* Line 6: `H` does not need `()`
* Line 7: Change capital `V` to small `v`
