### ISSUE TITLE
Ideas for shortening v2

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#184]
Total Incoming/Outgoing Direct Trust -> Total In/Out Direct Trust & remove "notation"

**Comment by dionyziz** [comment]
Remove "We also define a player’s assets to be the sum of her capital and her total outgoing trust."

**Comment by dionyziz** [comment]
Remove assets

**Comment by OrfeasLitos** [comment]
Remove Appendix references from proceedings version.

**Comment by OrfeasLitos** [comment]
The next theorem -> Theorem 1 before Trust Convergence Theorem, top of page 13
