### ISSUE TITLE
image for execution -> flow (trust flow)

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#19]
At proof of course

**Comment by dionyziz** [comment]
Are you sure we want to keep it like that? Wouldn't it be better to have a
full example with nodes partitioned into sets B and C and edges between
them?

**Comment by OrfeasLitos** [comment]
I was trying to choose between the two. The current one has the advantage that it is easier on the eye, covers all cases and points out more clearly the fact that sybil players _can't_ be trusted by legit players. The other has the advantage of a concrete example that requires less thought. I decided on the first because it is in the proof, where we have to be more formal, and not in the main body, where we should be more illustrative. What do you think?

**Comment by dionyziz** [comment]
Can you try making a good alternative? Then we can compare the two and see
how it looks like. I would like to have a concrete example, but I'm afraid
it will look too convoluted.

**Comment by OrfeasLitos** [comment]
![transgameflowconcretefigure](https://cloud.githubusercontent.com/assets/18602747/19805477/a094c4e2-9d0c-11e6-9b1c-88c3a5672ce3.png)

What do you think? It's not yet finely tweaked by messing with tikz, but you get the idea.

I also used E instead of B in the proof, as per figure and lemma formulation.

**Comment by OrfeasLitos** [comment]
The choice we make here should be consistent with the corresponding choice for the figure in the sybil resilience proof (p. 30)
