### ISSUE TITLE
References

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#3]
* URL references must be visible in print, see [APA formatting URLs](http://www.easybib.com/reference/guide/apa/website)
* Include previous attempts of reputation / trust networks (others work.txt must be embedded in references)

**Comment by dionyziz** [comment]
http://www.apastyle.org/learn/quick-guide-on-references.aspx

**Comment by dionyziz** [comment]
http://www2.isu.edu/success/writing/handouts/comparing_citation.pdf

**Comment by dionyziz** [comment]
Lines of credit: https://gist.github.com/drwasho/2c40b91e169f55988618#part-3-web-of-credit

**Comment by OrfeasLitos** [comment]
Check that they are ok
