### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#4]

**Comment by OrfeasLitos** [comment]
Maybe we can avoid related work whatsoever.

**Comment by OrfeasLitos** [comment]
notes_on_others

**Comment by OrfeasLitos** [comment]
Mention that previous approaches to reputation were before bitcoin, so there didn't exist a method for proof of risk.

**Comment by dionyziz** [comment]
This is the only section of the paper that is really missing. Let's get a sketch going?

**Comment by OrfeasLitos** [comment]
A deep and scary Rabbit Hole was discovered while looking for relevant work. Shall the user engage in further interaction with said Rabbit Hole?

**Comment by dionyziz** [comment]
What did you find?

**Comment by OrfeasLitos** [comment]
U. Maurer, “Modelling a Public-Key Infrastructure”, ESORICS’96, 1996

**Comment by OrfeasLitos** [comment]
right now notes_on_others contain ~20 papers and systems... It's impossible to cite and compare them all with our approach without exceeding the pages.

**Comment by OrfeasLitos** [comment]
We have a 1st draft!

**Comment by dionyziz** [comment]
You can reference them without much discussion. We need to show that we are
aware of previous works. We could say something like "Previous reputation
systems have not quantified trust financially [0][1][2][3][4][5]". No need
to say something about every single one individually.

**Comment by OrfeasLitos** [comment]
So you're suggesting to make this shorter? Great!

**Comment by OrfeasLitos** [comment]
If we go for brevity, this is a good idea:

"We know you [0,1,2,..,20] tried."

**Comment by OrfeasLitos** [comment]
https://openreputation.net/ I wanted to cite this one, but it is not actively developed, it is actually abandoned and Scholar doesn't find it. Also the paper quality is low. However, it is the only that explicitly targets reputation of IoT items and someone is still paying to keep the site running. I will include it with a link, if you think it's not worth it tell me.

**Comment by OrfeasLitos** [comment]
2nd draft, much closer to final form
