### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#42]
In abstract:

"Our system allows for concrete financial decision on the monetary amount a pseudonymous party can be trusted with" -> "Our system allows for concrete financial **decisions** on the monetary amount a pseudonymous party can be trusted with"

**Comment by dionyziz** [comment]
Also, this needs to be an implication:

<img width="316" alt="screen shot 2016-10-21 at 00 31 11" src="https://cloud.githubusercontent.com/assets/544572/19578737/babcd3ce-9725-11e6-8c81-4a35d4c3bd9a.png">

**Comment by dionyziz** [comment]
Missing `)` in if:

<img width="455" alt="screen shot 2016-10-21 at 00 56 21" src="https://cloud.githubusercontent.com/assets/544572/19579408/3e659e6a-9729-11e6-8390-e32a6ab73eb8.png">

**Comment by dionyziz** [comment]
The right hand side should say j-1:

<img width="433" alt="screen shot 2016-10-21 at 01 01 00" src="https://cloud.githubusercontent.com/assets/544572/19579540/e480191a-9729-11e6-9412-669609e0f9ea.png">

**Comment by dionyziz** [comment]
In the game code, this should say A:

<img width="415" alt="screen shot 2016-10-21 at 01 02 52" src="https://cloud.githubusercontent.com/assets/544572/19579576/1d5a42e2-972a-11e6-85e5-993926d7c206.png">

**Comment by dionyziz** [comment]
<img width="583" alt="screen shot 2016-10-21 at 01 03 43" src="https://cloud.githubusercontent.com/assets/544572/19579607/3d9b678e-972a-11e6-843c-003a80bda488.png">

**Comment by dionyziz** [comment]
We should use an actual arrow for this instead of `<-`

<img width="145" alt="screen shot 2016-10-21 at 01 06 11" src="https://cloud.githubusercontent.com/assets/544572/19579684/98a95668-972a-11e6-949a-e5b72ede1236.png">

**Comment by dionyziz** [comment]
Letter spacing is incorrect within algorithms. When mathematical operators are used like here, appropriate spacing must be attended to left and right:

<img width="245" alt="screen shot 2016-10-21 at 01 07 22" src="https://cloud.githubusercontent.com/assets/544572/19579713/be4a7f00-972a-11e6-94e2-d26d81208838.png">

Similar to all other operators such as set minus and the dollar-arrow.

**Comment by dionyziz** [comment]
Damage subscripts:

<img width="824" alt="screen shot 2016-10-21 at 01 24 00" src="https://cloud.githubusercontent.com/assets/544572/19580146/176eb720-972d-11e6-8bd1-cd3979114fd4.png">

In the `> 0` case of the function definition, the subscript should be `v,j-1`.

**Comment by OrfeasLitos** [comment]
All fixed

**Comment by dionyziz** [comment]
Two QED boxes

<img width="574" alt="screen shot 2016-10-24 at 00 38 04" src="https://cloud.githubusercontent.com/assets/544572/19629662/552d8ff8-9982-11e6-9575-27e993e10453.png">

**Comment by dionyziz** [comment]
The multisig members of these UTXOs are incorrect (spotted by @gubatron, thanks!)

<img width="274" alt="screen shot 2016-10-24 at 00 40 58" src="https://cloud.githubusercontent.com/assets/544572/19629670/94baa69c-9982-11e6-92bf-4d337c52422f.png">

**Comment by OrfeasLitos** [comment]
Oops, fixed. The double qeds appeared because the package amsthm was added and changed the proof environment definition. Sometimes I honestly hate the way tex is made... You just have to google a lot to find a solution that doesn't make much sense but just works.

**Comment by dionyziz** [comment]
your dash is rendering incorrectly

<img width="469" alt="screen shot 2016-10-28 at 23 55 27" src="https://cloud.githubusercontent.com/assets/544572/19823649/0e51f7c2-9d6a-11e6-93e9-bfe7dd20fcfd.png">

**Comment by OrfeasLitos** [comment]
Wow, the terminal renders it well, but not tex... I am still at a loss as to why tex is still so buggy...

Btw, found a funny bug in dot2texi: When I want a border around a cluster, if the label of some node is too big, the border doesn't appear. Removing one character from the label "fixes" it and the border appears...
