### ISSUE TITLE
Why should we limit oracles knowledge?

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#48]
You require that the oracles don't have access except to their local neighbourhood. While our particular oracles do not make use of non-local information, our model should not eliminate the possibility. I think we can remove this text:

<img width="826" alt="screen shot 2016-10-21 at 00 02 22" src="https://cloud.githubusercontent.com/assets/544572/19577854/ac6bd38c-9721-11e6-86b9-84c2754b14df.png">

**Comment by OrfeasLitos** [comment]
But that's the goal! To limit each node to its neighbourhood.

**Comment by dionyziz** [comment]
Not sure why, let's discuss this in tonight's meeting.
