### ISSUE TITLE
Mention that the graph is updated in each turn

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#51]
In the turn definition, we should say that the graph of the next turn is updated.

<img width="558" alt="screen shot 2016-10-21 at 00 11 31" src="https://cloud.githubusercontent.com/assets/544572/19578123/f4c5a0ee-9722-11e6-8cf8-a287eb5a9777.png">

Perhaps even a diagram could work well in this section, for example with a set of 2 steal actions being applied and graphs G_0 and G_1 being shown.

We should also mention that the capitals are updated in each turn. It is shown in the equations, but a textual description would be nice. Instead of saying "It holds that: (equation)", we could say "Capital is updated in every round: (equation)"

**Comment by OrfeasLitos** [comment]
The image is better than the examples
