### ISSUE TITLE
This formalism is unnecessary

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#52]
We can remove it or move it to the appendix:

<img width="822" alt="screen shot 2016-10-21 at 00 24 04" src="https://cloud.githubusercontent.com/assets/544572/19578543/cc4e58de-9724-11e6-85b1-8a516064b68a.png">

**Comment by OrfeasLitos** [comment]
It will go to the appendix when we decide how to move big definitions there.
