### ISSUE TITLE
Define global variable PrevOutTrust

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#54]
PrevOutTrust is treated like a global variable. This is unacceptable. We should fix it by allowing the oracle to maintain some "aux" data that it returns and it is given during its next execution.

<img width="581" alt="screen shot 2016-10-21 at 00 37 59" src="https://cloud.githubusercontent.com/assets/544572/19578939/ba3c7fc0-9726-11e6-812b-79ddd7c8b0b9.png">

**Comment by OrfeasLitos** [comment]
I tried another solution, because I think this gets more complicated than it should.
