### ISSUE TITLE
SelectSteal call simplification

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#56]
This call can be simplified:

<img width="854" alt="screen shot 2016-10-21 at 00 43 40" src="https://cloud.githubusercontent.com/assets/544572/19579085/71131bf0-9727-11e6-822c-509249c6c832.png">

To something like this:

```
y = SelectSteal(G_j, A, Damage)
```

Additionally, at the explanation below, we should state that the SelectState function can be arbitrarily defined by the conservative player and it does not matter how conservation of trust is allocated for our proofs. (It is mentioned earlier in passing, but at this stage I think it is better to state it clearly).

**Comment by OrfeasLitos** [comment]
Fixed. Also added a comment to show what y is after the change.
