### ISSUE TITLE
Introduction: Bootstrapping the network

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#57]
We should mention in the introduction that the network must be bootstrapped by people originally extending trust to each other. Then the network can evolve and can be used to purchase goods. Somehow we can mention that it could start from local groups of friends or universities?

@gubatron & @TheCharlatan had some comments on this.

**Comment by OrfeasLitos** [comment]
How can I allow them to comment here?

**Comment by dionyziz** [comment]
We decided not to delve into this discussion too much – it should become clearer from the new introduction how initial trust is distributed by a player.
