### ISSUE TITLE
vOracle = idleOracle?

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#59]
I don't think this comment is true. Individual players can be conservative, which are not idle.

<img width="868" alt="screen shot 2016-10-21 at 01 11 14" src="https://cloud.githubusercontent.com/assets/544572/19579859/6948e3b0-972b-11e6-9232-7faa622bbe7a.png">

**Comment by OrfeasLitos** [comment]
That was dumb.
