### ISSUE TITLE
in_v,j == 0 check unnecessary

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#62]
In the happy/sad/angry game, I think the left portion of the && in this if is not necessary:

<img width="474" alt="screen shot 2016-10-21 at 01 19 29" src="https://cloud.githubusercontent.com/assets/544572/19580045/7eb5a368-972c-11e6-8a4f-17686e6d3246.png">

if `loss` is positive, then `in` must necessarily be 0 since the player who just played is conservative.

**Comment by OrfeasLitos** [comment]
That's just a sanity check. Should it not be there? I like sanity checks.

**Comment by dionyziz** [comment]
Use a comment or `assert(...)`

**Comment by OrfeasLitos** [comment]
used a comment to save a line
