### ISSUE TITLE
Remove unneeded assumption in sybil theorem proof

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#64]
I don't think we're using this anywhere in the proof, so let's remove it:

<img width="831" alt="screen shot 2016-10-21 at 01 47 22" src="https://cloud.githubusercontent.com/assets/544572/19580649/548f12b4-9730-11e6-9704-d22855e1b83a.png">

**Comment by OrfeasLitos** [comment]
done
