### ISSUE TITLE
Remove last line of theorems

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#66]
Many of the theorems in the paper finish with the theorem statement. This is unnecessary and takes up some space. We can replace it with something like "This proves the theorem." For example here:

<img width="865" alt="screen shot 2016-10-21 at 01 55 28" src="https://cloud.githubusercontent.com/assets/544572/19580817/76e4e234-9731-11e6-9e85-47f15d1cd636.png">

**Comment by OrfeasLitos** [comment]
Already done for proofs ouside of the appendix

**Comment by OrfeasLitos** [comment]
done it in the appendix too
