### ISSUE TITLE
universities, mails in one line each

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#70]

**Comment by dionyziz** [comment]
Seems that they're wrapping around now, so we'll have to split them into two lines again. Oh well. But at least the lack of superscripts makes it look cleaner, let's keep it.

**Comment by OrfeasLitos** [comment]
We gain 1 line this way. Not very pretty, but a line is a line. Close it if you agree.

**Comment by dionyziz** [comment]
Here, "Athens" is in its own line. We can just move the whole uni in its own line and make it prettier without losing any space.

<img width="571" alt="screen shot 2016-10-22 at 16 22 04" src="https://cloud.githubusercontent.com/assets/544572/19619586/b3d37a78-9873-11e6-8d47-c9250ee24fcc.png">

**Comment by OrfeasLitos** [comment]
Ok, fixed it. No putting the superscripts back? It's part of lncs...
