### ISSUE TITLE
add risk invariance theorem

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#79]

**Comment by OrfeasLitos** [comment]
Between trust flow and trust to multiple players

**Comment by OrfeasLitos** [comment]
![riskinv](https://cloud.githubusercontent.com/assets/18602747/19626022/8d7db81e-991f-11e6-8f36-1894f523a640.png)
This is the formulation. It seems that we have two choices for the proof: A constructive proof like fcfs or prop algorithm, or a nonconstructive proof that needs the fact that maxFlow(A,B) is a continuous function of the outgoing trusts of A.

**Comment by dionyziz** [comment]
Let's formulate it as follows:

```
Let $\matcal{G}$ be a game graph, $A, B \in \mathcal{V}, F = Tr_{A -> B}$ and $V \leq F$ the desired value to be transferred from $A$ to $B$. Then let $\mathcal{G'}$ be a new graph such that:

$\mathcal{V'} = \mathcal{V}$
$\forall v \in \mathcal{V'} \setminus \{A\}, w \in \mathcal{V}', DTr'_{v -> w} = DTr_{v -> w}$

Let $DTr'_{A -> v}$ be an assignment such that $Tr'_{A -> B} = F - V$.

Let $\mathcal{G''}$ be a graph exactly equal to $\mathcal{G'}$ except for the following change:

$DTr''_{A -> B} = DTr_{A -> B} + V$

Then $Tr''_{A -> B} = Tr_{A -> B}$.
```

This theorem just states that trust remains invariant *if* we are able to construct a change in the flows. The fact that this is constructible could be part of the appendix or wait for our next paper on the algorithms.

**Comment by OrfeasLitos** [comment]
We have to note also that DTr'_{A -> B} = DTr_{A -> B}, or else DTr'_{A -> B} may be recalculated in a way that the final result doesn't hold.

**Comment by OrfeasLitos** [comment]
Oh _italics_ with underscore...

**Comment by OrfeasLitos** [comment]
Actually my previous comment is wrong as well, because if DTr'{A -> B} = DTr{A -> B}, then maybe it's impossible to find the desired assignment. I think that the correct assumption is DTr''{A -> B} = DTr'{A -> B} + V.

**Comment by OrfeasLitos** [comment]
Suppose {A -> B} everywhere. The last idea works in the simple case that Tr = DTr, because then DTr' = DTr - V and Tr'' = DTr'' = DTr' + V = DTr - V + V = DTr = Tr.

**Comment by OrfeasLitos** [comment]
Revised and proved it.
