### ISSUE TITLE
Future work

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#82]
Implementation, experimental results, extend game theoretic approach, dynamic setting, trust manipulation algorithms, zero knowledge, other multisig types

**Comment by dionyziz** [comment]
Don't have a separate section for each of these, just use a couple of paragraphs to save some space.

**Comment by OrfeasLitos** [comment]
1st version ready!

**Comment by dionyziz** [comment]
It looks very laconic. If I didn't already know what you were meaning, I couldn't infer the open problems. The writing style in the previous formulation is better. We can try shortening it after it is well written.

**Comment by OrfeasLitos** [comment]
Extended it, still needs improvement

**Comment by OrfeasLitos** [comment]
Tried it once more, could be further improved. I wait for recommendations.
