### ISSUE TITLE
forall , or :

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#86]
I know you prefer "," after the $\forall$ quantifier for readability corresponding to natural language, but for example in this case it takes some time for the reader to notice if the forall's variable binding part ends in the first or in the second comma:

<img width="353" alt="screen shot 2016-10-24 at 00 44 11" src="https://cloud.githubusercontent.com/assets/544572/19629699/02120078-9983-11e6-81cd-0da781c8ae11.png">

I suggest we change forall to read as $\forall x: P(x)$. This will also make it consistent with our $\exists$ syntax.

**Comment by OrfeasLitos** [comment]
It doesn't help readability though. In the example above we can simply add another \forall before w.

**Comment by dionyziz** [comment]
OK
