### ISSUE TITLE
Paper too long for submission - shortening ideas

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#87]
Remove Execute Turn algorithm, use validate and commit turn algorithms directly in TrustIsRisk Game.

Done

**Comment by OrfeasLitos** [comment]
do away with line 1 in conservative oracle by using Damage_{A, j}

**Comment by OrfeasLitos** [comment]
remove output from the Transitive Game. Either way it never returns.

**Comment by OrfeasLitos** [comment]
Single-line if/for/while blocks with content of one line. Reduces readability.

**Comment by OrfeasLitos** [comment]
Remove "For the complete proof, see Appendix" after proof sketches.

**Comment by OrfeasLitos** [comment]
Move related work to appendix...

**Comment by OrfeasLitos** [comment]
It seems we have a problem with space. The work is 18 pages long with only 2 images out of the 4-5 we wish to include. Admittedly the second image is too big, but it isn't more-than-one-page-big.

**Comment by OrfeasLitos** [comment]
Any comment on a possible way to rephrase anything so as to shorten it would be greatly appreciated.

**Comment by OrfeasLitos** [comment]
Trust flow theorem's proof to appendix, substitute with proof sketch

**Comment by OrfeasLitos** [comment]
move commit, validate turn to appendix, simply describe them in the main body

**Comment by OrfeasLitos** [comment]
The fact that this system can function in a completely decentralized fashion will become clear in the following sections. We prove this result in the Sybil Resilience Theorem (\ref{sybil}).

->

The fact that this system can function in a completely decentralized fashion will be shown through the Sybil Resilience Theorem(\ref{sybil}).

**Comment by OrfeasLitos** [comment]
Remove Players definition

**Comment by dionyziz** [comment]
remove return-after-else

**Comment by dionyziz** [comment]
Eliminate top/bottom margins around images.

**Comment by dionyziz** [comment]
This equation is unnecessary – damage is defined previously anyway.

<img width="713" alt="screen shot 2016-10-27 at 09 16 18" src="https://cloud.githubusercontent.com/assets/544572/19757944/110d9ec0-9c26-11e6-8421-c75c697756f8.png">

**Comment by dionyziz** [comment]
The else case is sufficient for both:

<img width="736" alt="screen shot 2016-10-27 at 09 17 40" src="https://cloud.githubusercontent.com/assets/544572/19757968/3c1edd36-9c26-11e6-8cf0-5a5c9a8478ef.png">

**Comment by dionyziz** [comment]
The second case is equivalent to both here:

<img width="713" alt="screen shot 2016-10-27 at 09 18 39" src="https://cloud.githubusercontent.com/assets/544572/19757986/5dfba18c-9c26-11e6-8b1f-9e657591ddf4.png">

**Comment by OrfeasLitos** [comment]
When risk invariance proof is moved to appendix, we are at 17.5 pages with all shapes done! The related work should not be more than half page, so there will be 3 pages more...

**Comment by dionyziz** [comment]
Look at KLS paper for typesetting deviations from FC template that would save us space. For example inline equations, avoiding numbering, code rendering, figures margins etc.

**Comment by dionyziz** [comment]
The whitespace around some equations is extremely large:

<img width="522" alt="screen shot 2016-10-28 at 17 06 33" src="https://cloud.githubusercontent.com/assets/544572/19811274/f31bd042-9d30-11e6-84be-35c4116c4747.png">

**Comment by OrfeasLitos** [comment]
this whitespace is automatically generated because of the figure in the next page.

**Comment by dionyziz** [comment]
Surely the header of the next section and the first two lines could be moved to the page eliminating some of the whitespace leaving the figure where it is?

**Comment by OrfeasLitos** [comment]
haha yes. After final reductions, just to be sure that it doesn't move up by itself.

**Comment by dionyziz** [comment]
Y_{st} = Y_{add} = 0

**Comment by dionyziz** [comment]
This input line can be made into one line I think:

<img width="515" alt="screen shot 2016-10-29 at 01 03 39" src="https://cloud.githubusercontent.com/assets/544572/19824867/9085b144-9d73-11e6-969c-7ceff05bc7e8.png">

"old graph" -> "old"
"old capital" -> "old"
"ProvisionalTurn" -> Turn

**Comment by OrfeasLitos** [comment]
Move all algorithms to Appendix

**Comment by OrfeasLitos** [comment]
We are now at 18.5 pages, considering the risk invariance proof moved.

**Comment by OrfeasLitos** [comment]
Heavy cuts on further research

**Comment by dionyziz** [comment]
Yep, further research should be just one section, not separate ones.

**Comment by OrfeasLitos** [comment]
Just uniting the sections saves half a page.

**Comment by OrfeasLitos** [comment]
We are at 17 pages. It seems that the algorithms must be removed. Then maybe we get the desired length.

**Comment by OrfeasLitos** [comment]
Moving the algorithms to the appendix did it! Now we are just under 15 pages.

**Comment by OrfeasLitos** [comment]
We would like to maintain the Transitive Game in the main body.
