### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#88]
Let's run the whole paper through a spellchecker to avoid typos like this:

<img width="474" alt="screen shot 2016-10-26 at 10 49 45" src="https://cloud.githubusercontent.com/assets/544572/19719389/fa8227fa-9b69-11e6-80ab-1e23deb97585.png">

**Comment by OrfeasLitos** [comment]
corrected posesses -> possesss, unaccessible -> inaccessible, addreses -> addresses. Thanks to WhiteSmoke.
