### ISSUE TITLE
Player subscript in Damage

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#91]
Why do we need the player A subscript in Damage? Isn't it always equal to Player(j), where j is either specified as a subscript or implied?

<img width="588" alt="screen shot 2016-10-26 at 15 55 20" src="https://cloud.githubusercontent.com/assets/544572/19728713/bd3da34e-9b94-11e6-9f34-b4f35d6b1cb9.png">

**Comment by OrfeasLitos** [comment]
You're right, it's not necessary. However, it improves readability and it clarifies that the Damage concerns only player A. The problem is that it is not well defined when `Player(j) != A`. Tell me your opinion.

**Comment by dionyziz** [comment]
OK
