### ISSUE TITLE
History indexing

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#92]
This notation is rather unclear:

<img width="68" alt="screen shot 2016-10-26 at 15 58 54" src="https://cloud.githubusercontent.com/assets/544572/19728825/1ef1aea0-9b95-11e6-9c2f-4f39eb6cf978.png">

Since history is altered in CommitTurn, we could even remove these indices completely. Alternatively, we could use a subscript like this: `$\mathcal(H)_{1...j - 1}`

**Comment by OrfeasLitos** [comment]
I added these indexes to clarify which part of the history is input. I will change it to your suggestion.
