### ISSUE TITLE
Simplify trust converge theorem statement

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#94]
This assumption is not necessary for the statement of the theorem; just say that there is some j' such that $\forall j > j': Turn_j = \emptyset$. The fact that $j' > j_0$ is irrelevant for our proofs. 

<img width="595" alt="screen shot 2016-10-26 at 16 08 24" src="https://cloud.githubusercontent.com/assets/544572/19729199/7ad733a6-9b96-11e6-84c1-e6c6ad3e1f6f.png">

**Comment by OrfeasLitos** [comment]
Good one.
