### ISSUE TITLE
Max flow explanation

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#95]
Max flow must be introduced more smoothly. This algorithm / problem is not known in all of the bitcoin community. State the problem in a short sentence and give a reference.

**Comment by OrfeasLitos** [comment]
It's already there. It needs further explanation?

**Comment by dionyziz** [comment]
Where?

**Comment by OrfeasLitos** [comment]
![maxflow](https://cloud.githubusercontent.com/assets/18602747/19733260/608cfcba-9b9b-11e6-8d74-37a3137236dd.png)

on page 12. Not explicative enough? Remember, we' re short on space and a decent example must contain an image...

**Comment by dionyziz** [comment]
"Let G be a weighted directed graph. According to [9] p. 709, if we consider each edge’s capacity as its weight (∀e ∈ E(G), ce = c(e)), we say that a flow assignment X = [xvw]V (F G)×V (F G) with a source A and a sink B is valid when"

Let's rewrite this as:

"Let G be a weighted directed graph. We will investigate the max flow on this graph. For an introduction to the max flow problem, see [9] p. 709. Considering each edge’s capacity as its weight, a flow assignment $X = [xvw]V×V$ with source A and sink B is valid when"

**Comment by dionyziz** [comment]
(and remove the phrase "For more details on this algorithm, please refer to [9] p. 708 and
on." from later in the same paragraph)
