### ISSUE TITLE
Avoid repeating transitive game definition

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#97]
You are repeating the transitive game definition again here:

<img width="601" alt="screen shot 2016-10-26 at 17 16 22" src="https://cloud.githubusercontent.com/assets/544572/19732112/021c6db4-9ba0-11e6-90cc-273b31cfe14b.png">

**Comment by OrfeasLitos** [comment]
Open it again if you find more
