### ISSUE TITLE
FG is not defined here

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#98]
Your graph is called G, this should be reflected below:

<img width="593" alt="screen shot 2016-10-26 at 17 19 05" src="https://cloud.githubusercontent.com/assets/544572/19732203/53cfa2c0-9ba0-11e6-95ec-c0d8de8ea676.png">

I think we can also use V directly instead of V(G). Similarly for E.

**Comment by OrfeasLitos** [comment]
Dropped the parenthesis. Also changed the \mathcal{V},{E} to simple V, E in the next paragraph.
