### ISSUE TITLE
Avoid turn index in Lemma 1

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#99]
In this lemma, we can just say Let $\mathcal{G}$ be a game graph...

<img width="588" alt="screen shot 2016-10-26 at 18 23 15" src="https://cloud.githubusercontent.com/assets/544572/19734818/4d6a9648-9ba9-11e6-9e7e-42f16568c0ab.png">

Why do we need turns in the theorem statement? Or at least use turn 0 in the theorem statement for simplicity. What do you think?

**Comment by OrfeasLitos** [comment]
Done. Changed accordingly the corresponding proof.
